Repository najasin/na-jasin-be, pull requests merged in 2023-08, with the labels that each got.

#4 Feature: #2 기본 설정 및 global Bean 구현
  build.gradle
  src/main/java/com/najasin/config/JpaConfig.java
  src/main/java/com/najasin/config/QuerydslConfig.java
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/global/aspect/LoggingAspect.java
  src/main/java/com/najasin/global/audit/AuditEntity.java
  src/main/java/com/najasin/global/response/ApiResponse.java
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: v1.0, feature, chore

#6 Feature: #3 User 관련 비즈니스 로직 구현
  build.gradle
  src/main/java/com/najasin/config/WebClientConfig.java
  src/main/java/com/najasin/domain/user/entity/Oauth2Entity.java
  src/main/java/com/najasin/domain/user/entity/User.java
  src/main/java/com/najasin/domain/user/entity/enums/Provider.java
  src/main/java/com/najasin/domain/user/entity/enums/Role.java
  src/main/java/com/najasin/domain/user/repository/UserRepository.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/main/java/com/najasin/security/oauth/dto/request/OAuth2Request.java
  src/test/java/com/najasin/service/UserServiceTest.java
Labels: v1.0, feature, chore

#7 Feature: #3 소셜 로그인 및 JWT 발급, 인증 로직 구현
  src/main/java/com/najasin/config/JwtKeyConfig.java
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/domain/user/repository/UserRepository.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/main/java/com/najasin/global/aspect/LoggingAspect.java
  src/main/java/com/najasin/security/jwt/dto/JwtToken.java
  src/main/java/com/najasin/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/najasin/security/jwt/service/JwtGenerateService.java
  src/main/java/com/najasin/security/jwt/util/JwtProvider.java
  src/main/java/com/najasin/security/jwt/util/JwtValidator.java
  src/main/java/com/najasin/security/model/OAuth2Request.java
  src/main/java/com/najasin/security/model/PrincipalUser.java
  src/main/java/com/najasin/security/oauth/common/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/najasin/security/oauth/common/mapper/AttributeMapper.java
  src/main/java/com/najasin/security/oauth/common/mapper/AttributeMapperFactory.java
  src/main/java/com/najasin/security/oauth/common/mapper/GoogleAttributeMapper.java
  src/main/java/com/najasin/security/oauth/common/mapper/KakaoAttributeMapper.java
  src/main/java/com/najasin/security/oauth/common/mapper/PrincipalUserMapper.java
  src/main/java/com/najasin/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/najasin/security/oauth/service/CustomOidcUserService.java
  src/main/resources/application-local.yml
  src/test/java/com/najasin/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: v1.0, feature, refactor, chore

#21 Fix: #17 keyword percent를 origin과 others로 분리
  src/main/java/com/najasin/domain/dto/KeywordDTO.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/main/java/com/najasin/domain/userKeyword/entity/UserKeyword.java
  src/main/java/com/najasin/domain/userKeyword/service/UserKeywordService.java
  src/test/java/com/najasin/service/UserKeywordServiceTest.java
  src/test/java/com/najasin/service/UserServiceTest.java
Labels: v1.0, fix

#22 Feature: #18 타적나사를 위한 서비스 구현
  src/main/java/com/najasin/domain/comment/entity/Comment.java
  src/main/java/com/najasin/domain/comment/entity/CommentId.java
  src/main/java/com/najasin/domain/comment/repository/CommentRepository.java
  src/main/java/com/najasin/domain/comment/service/CommentService.java
  src/main/java/com/najasin/domain/keyword/entity/Keyword.java
  src/main/java/com/najasin/domain/question/entity/Question.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/test/java/com/najasin/service/AnswerServiceTest.java
  src/test/java/com/najasin/service/CommentServiceTest.java
  src/test/java/com/najasin/service/UserKeywordServiceTest.java
Labels: v1.0, feature

#26 Fix: #11 Prod yml 파일에 elastic cache for redis 설정 추가
  src/main/resources/appliacation-prod.yml
  src/main/resources/application-prod.yml
Labels: v1.0, fix

#27 Feature: #14 회원가입 및 로그인 dto 수정
  src/main/java/com/najasin/domain/user/controller/UserController.java
  src/main/java/com/najasin/security/oauth/common/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/najasin/security/oauth/dto/response/OAuth2Response.java
Labels: v1.0, fix

#28 Feature: #15 UserType 변경 로직 구현
  src/main/java/com/najasin/domain/user/entity/User.java
  src/main/java/com/najasin/domain/userType/entity/UserType.java
  src/main/java/com/najasin/domain/userType/repository/UserTypeRepository.java
  src/main/java/com/najasin/domain/userType/service/UserTypeService.java
  src/main/java/com/najasin/domain/userUserType/controller/UserUserTypeController.java
  src/main/java/com/najasin/domain/userUserType/dto/message/UserTypeMessage.java
  src/main/java/com/najasin/domain/userUserType/dto/request/UserTypeUpdateRequest.java
  src/main/java/com/najasin/domain/userUserType/dto/response/UserTypeResponse.java
  src/main/java/com/najasin/domain/userUserType/repository/UserUserTypeRepository.java
  src/main/java/com/najasin/domain/userUserType/service/UserUserTypeService.java
  src/test/java/com/najasin/service/UserTypeServiceTest.java
  src/test/java/com/najasin/service/UserUserTypeServiceTest.java
Labels: v1.0, feature

#29 Deploy: develop to master
  src/main/java/com/najasin/domain/comment/entity/Comment.java
  src/main/java/com/najasin/domain/comment/entity/CommentId.java
  src/main/java/com/najasin/domain/comment/repository/CommentRepository.java
  src/main/java/com/najasin/domain/comment/service/CommentService.java
  src/main/java/com/najasin/domain/dto/KeywordDTO.java
  src/main/java/com/najasin/domain/keyword/entity/Keyword.java
  src/main/java/com/najasin/domain/question/entity/Question.java
  src/main/java/com/najasin/domain/user/controller/UserController.java
  src/main/java/com/najasin/domain/user/entity/User.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/main/java/com/najasin/domain/userKeyword/entity/UserKeyword.java
  src/main/java/com/najasin/domain/userKeyword/service/UserKeywordService.java
  src/main/java/com/najasin/domain/userType/entity/UserType.java
  src/main/java/com/najasin/domain/userType/repository/UserTypeRepository.java
  src/main/java/com/najasin/domain/userType/service/UserTypeService.java
  src/main/java/com/najasin/domain/userUserType/controller/UserUserTypeController.java
  src/main/java/com/najasin/domain/userUserType/dto/message/UserTypeMessage.java
  src/main/java/com/najasin/domain/userUserType/dto/request/UserTypeUpdateRequest.java
  src/main/java/com/najasin/domain/userUserType/dto/response/UserTypeResponse.java
  src/main/java/com/najasin/domain/userUserType/repository/UserUserTypeRepository.java
  src/main/java/com/najasin/domain/userUserType/service/UserUserTypeService.java
  src/main/java/com/najasin/security/oauth/common/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/najasin/security/oauth/dto/response/OAuth2Response.java
  src/main/resources/appliacation-prod.yml
  src/main/resources/application-prod.yml
  src/test/java/com/najasin/service/AnswerServiceTest.java
  src/test/java/com/najasin/service/CommentServiceTest.java
  src/test/java/com/najasin/service/UserKeywordServiceTest.java
  src/test/java/com/najasin/service/UserServiceTest.java
  src/test/java/com/najasin/service/UserTypeServiceTest.java
  src/test/java/com/najasin/service/UserUserTypeServiceTest.java
Labels: v1.0

#31 Deploy: develop to master
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/domain/answer/dto/AnswerDTO.java
  src/main/java/com/najasin/domain/answer/entity/AnswerId.java
  src/main/java/com/najasin/domain/answer/repository/AnswerRepository.java
  src/main/java/com/najasin/domain/answer/service/AnswerService.java
  src/main/java/com/najasin/domain/character/CharacterService.java
  src/main/java/com/najasin/domain/character/body/entity/Body.java
  src/main/java/com/najasin/domain/character/body/repository/BodyRepository.java
  src/main/java/com/najasin/domain/character/characterset/entity/CharacterSet.java
  src/main/java/com/najasin/domain/character/characterset/repository/CharacterSetRepository.java
  src/main/java/com/najasin/domain/character/dto/AllCharacterItems.java
  src/main/java/com/najasin/domain/character/dto/CharacterDTO.java
  src/main/java/com/najasin/domain/character/dto/CharacterInfoDTO.java
  src/main/java/com/najasin/domain/character/expression/entity/Expression.java
  src/main/java/com/najasin/domain/character/expression/repository/ExpressionRepository.java
  src/main/java/com/najasin/domain/character/face/entity/Face.java
  src/main/java/com/najasin/domain/character/face/repository/FaceRepository.java
  src/main/java/com/najasin/domain/comment/entity/Comment.java
  src/main/java/com/najasin/domain/comment/service/CommentService.java
  src/main/java/com/najasin/domain/keyword/dto/KeywordDTO.java
  src/main/java/com/najasin/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/najasin/domain/question/entity/Question.java
  src/main/java/com/najasin/domain/question/repository/QuestionRepository.java
  src/main/java/com/najasin/domain/question/service/QuestionService.java
  src/main/java/com/najasin/domain/user/controller/UserController.java
  src/main/java/com/najasin/domain/user/dto/CharacterItem.java
  src/main/java/com/najasin/domain/user/dto/CharacterItems.java
  src/main/java/com/najasin/domain/user/dto/Page.java
  src/main/java/com/najasin/domain/user/dto/PageUpdateRequestDTO.java
  src/main/java/com/najasin/domain/user/dto/PutAnswer.java
  src/main/java/com/najasin/domain/user/dto/UserInfoResponse.java
  src/main/java/com/najasin/domain/user/dto/message/UserResponse.java
  src/main/java/com/najasin/domain/user/entity/User.java
  src/main/java/com/najasin/domain/user/entity/enums/UserType.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/main/java/com/najasin/domain/userKeyword/service/UserKeywordService.java
  src/main/java/com/najasin/domain/userUserType/entity/UserUserType.java
  src/main/java/com/najasin/domain/userUserType/entity/UserUserTypeId.java
  src/main/java/com/najasin/domain/userUserType/repository/UserUserTypeRepository.java
  src/main/java/com/najasin/domain/userUserType/service/UserUserTypeService.java
  src/test/java/com/najasin/service/AnswerServiceTest.java
  src/test/java/com/najasin/service/CharacterServiceTest.java
  src/test/java/com/najasin/service/CommentServiceTest.java
  src/test/java/com/najasin/service/QuestionServiceTest.java
  src/test/java/com/najasin/service/UserKeywordServiceTest.java
  src/test/java/com/najasin/service/UserServiceTest.java
  src/test/java/com/najasin/service/UserUserTypeServiceTest.java
Labels: v1.0

#32 Feature: #20 유저 인증 추가, lazy 로딩 설정
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/domain/user/controller/UserController.java
  src/main/java/com/najasin/domain/user/entity/User.java
  src/main/java/com/najasin/domain/userUserType/entity/UserUserType.java
  src/main/java/com/najasin/domain/userUserType/repository/UserUserTypeRepository.java
  src/main/java/com/najasin/domain/userUserType/service/UserUserTypeService.java
  src/test/java/com/najasin/service/UserUserTypeServiceTest.java
Labels: v1.0, feature

#33 Deploy: develop to master
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/domain/user/controller/UserController.java
  src/main/java/com/najasin/domain/user/entity/User.java
  src/main/java/com/najasin/domain/userUserType/entity/UserUserType.java
  src/main/java/com/najasin/domain/userUserType/repository/UserUserTypeRepository.java
  src/main/java/com/najasin/domain/userUserType/service/UserUserTypeService.java
  src/test/java/com/najasin/service/UserUserTypeServiceTest.java
Labels: v1.0

#36 fix(#34): cors에 모든 환경 추가
  src/main/java/com/najasin/config/WebConfig.java
Labels: v1.0

#37 fix(#34): cors에 모든 환경 추가
  src/main/java/com/najasin/config/WebConfig.java
  src/main/resources/application-prod.yml
Labels: v1.0

#38 Fix(34): success handler에 redirect 추가
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/config/WebConfig.java
  src/main/java/com/najasin/security/oauth/common/handler/CustomAuthenticationSuccessHandler.java
Labels: v1.0

#72 feature(#71): refresh token을 통한 access token 재발급 로직 구현
  src/main/java/com/najasin/config/SecurityConfig.java
  src/main/java/com/najasin/domain/user/controller/AuthController.java
  src/main/java/com/najasin/domain/user/dto/message/UserResponse.java
  src/main/java/com/najasin/domain/user/dto/response/AccessTokenGenerateResponse.java
  src/main/java/com/najasin/domain/user/service/AuthService.java
  src/main/java/com/najasin/domain/user/service/UserService.java
  src/main/java/com/najasin/global/advice/AuthControllerAdvice.java
  src/main/java/com/najasin/global/advice/JwtControllerAdvice.java
  src/main/java/com/najasin/security/jwt/util/JwtProvider.java
  src/main/java/com/najasin/security/jwt/util/JwtValidator.java
  src/main/resources/application-prod.yml
Labels: v1.0, feature
